[TP][OPS-11132]
hmrc/p800-refunds-frontend pull request #31
Opened 2023-11-10 15:51 UTC by tp10

2023-11-10 16:00 UTC, DarrenCB commented on app/language/Messages.scala
> +      english = "What did you think of this service ?"
Don't think we need a space before the ?

2023-11-10 16:14 UTC, DarrenCB submitted a review, later dismissed

2023-11-10 16:16 UTC, tp10 commented on app/language/Messages.scala
> +      english = "What did you think of this service ?"
Yip, good spot. I've added the copy to the test so pushing up again.

2023-11-10 16:16 UTC, DarrenCB approved these changes

2023-11-10 17:50 UTC, barnesjake commented on app/language/Messages.scala
> +      english = "takes 30 seconds"
should we have the brackets inside the message

2023-11-10 17:51 UTC, barnesjake requested changes
Could we have the brackets for "(takes 30 seconds)" inside the messages file, not the twirl template

2023-11-13 14:42 UTC, barnesjake approved these changes

2023-11-13 16:07 UTC, Lyrain approved these changes

2023-11-13 16:07 UTC, merged