[MO][OPS-11096] Added 'Do you want to sign in?' page
hmrc/p800-refunds-frontend pull request #8
Opened 2023-10-23 16:38 UTC by Lyrain

2023-10-24 08:33 UTC, barnesjake requested changes
Just in case we forget to change this later, we shouldn't point it to test only (although I'm not sure what else it should be)

2023-10-24 08:35 UTC, barnesjake commented
> Just in case we forget to change this later, we shouldn't point it to test only (although I'm not sure what else it should be)

Sorry this was supposed to be on line 36 on the do you want to sign in twirl template file (I'm using GitHub on mobile)

2023-10-25 09:03 UTC, AndyHWChung commented on app/language/LangMessages.scala
> +    english = "Sign in with your Government Gateway user ID. You'll have fewer details to enter this way."
is this a straight quote here? We should be using curly quotes like the ones described [here](https://smartquotesforsmartpeople.com/) for UI content

2023-10-25 09:19 UTC, barnesjake commented on app/forms/DoYouWantToSignInForm.scala
> +    signIn: Option[String]
https://github.com/hmrc/essttp-frontend/blob/main/app/models/forms/CanPayUpfrontForm.scala

Maybe something like this usage would be nice

2023-10-25 14:59 UTC, AndyHWChung commented on app/language/ErrorMessages.scala
> +  val `Select yes if you want to sign in to your tax account`: Message = Message(
don't know if this structure is deliberate but if I want to see all messages that can appear on a page having a separate `ErrorMessages` file makes that a bit difficult. Perhaps sticking everything in `LangMessages` and grouping together by page would make it easier, e.g.:
```scala
object LangMessages {

 Common {
    val continue: Message = ...
    val `There is a problem`: Message =
  }
  
 DoYouWantToSignIn {
    val `Sign in with your Government Gateway user ID.`: Message =
    val `Yes, sign in`: Message = ...
    val `No, continue without signing in`: Message = ...
    val `Select yes if you want to sign in to your tax account`: Message = ...
  }

  OtherPageInTheFuture { ... }

}
```
What do you think?

2023-10-25 16:55 UTC, barnesjake approved these changes

2023-10-25 17:17 UTC, AndyHWChung approved these changes

2023-10-26 08:06 UTC, merged